### ISSUE TITLE
INI Parser

### ISSUE THREAD

**Issue by xmonader** [codescalersinternships/home#1]
Implement iniparaser with compatible APIs with configparser library in python (reading: https://xmonader.github.io/nimdays/day05_iniparser.html )

- [ ] @OmarElawady 
- [ ] @Omarabdul3ziz 
- [ ] @omarelsheekh 
- [ ] @kirolosessam 

Code is done with proper tests and documentation and add repo link in a comment

**Comment by OmarElawady** [comment]
https://github.com/OmarElawady/ini-parser/

**Comment by omarelsheekh** [comment]
https://github.com/omarelsheekh/codescalers2019ini

**Comment by Omarabdul3ziz** [comment]
https://github.com/Omarabdul3ziz/ini_parser

**Comment by Abdelrahman-Kh-Fouad** [comment]
https://github.com/Abdelrahman-Kh-Fouad/Ini-parser
