### ISSUE TITLE
DMIDecode

### ISSUE THREAD

**Issue by xmonader** [codescalersinternships/home#3]
Implement dmidecode parser (reading: https://xmonader.github.io/nimdays/day01_dmidecode.html )

- [ ] @OmarElawady 
- [ ] @Omarabdul3ziz 
- [ ] @omarelsheekh 
- [ ] @kirolosessam 

Code is done with proper tests and documentation and add repo link in a comment

**Comment by OmarElawady** [comment]
https://github.com/OmarElawady/dmidecode

**Comment by omarelsheekh** [comment]
https://github.com/omarelsheekh/codescalers2019dmidecode

**Comment by Omarabdul3ziz** [comment]
https://github.com/Omarabdul3ziz/dmi_decode
