### ISSUE TITLE
CacheTable

### ISSUE THREAD

**Issue by xmonader** [codescalersinternships/home#4]
Implement cachetable with easy APIs where you can set global TTL (time to live) on the table itself or ttl per key 

- [ ] @OmarElawady 
- [ ] @Omarabdul3ziz 
- [ ] @omarelsheekh 
- [ ] @kirolosessam 

Considered done with code + tests + documentation

**Comment by OmarElawady** [comment]
https://github.com/OmarElawady/cachetable

**Comment by omarelsheekh** [comment]
https://github.com/omarelsheekh/codescalers2019cashtable
