### ISSUE TITLE
Setup Travis-CI and Codecov for your projects

### ISSUE THREAD

**Issue by xmonader** [codescalersinternships/home#5]
Investigate how to setup travis-ci and codecov for all of your projects so far (iniparser, cachetable, dmidecode)

- [ ] @OmarElawady 
- [ ] @Omarabdul3ziz 
- [ ] @omarelsheekh 
- [ ] @kirolosessam

**Comment by OmarElawady** [comment]
Done! Used Travis to install the requirements, run tests and upload coverage reports to Codecov.

**Comment by omarelsheekh** [comment]
done for ini,dmide & cashTable
