### ISSUE TITLE
LinksChecker for Static websites

### ISSUE THREAD

**Issue by xmonader** [codescalersinternships/home#7]
We usually maintain our websites in markdown format and use a static generator like hugo or jekyll to generate static website.

Write a tool to validate all the links referenced in our websites

 - [ ] @OmarElawady 
- [ ] @Omarabdul3ziz 
- [ ] @omarelsheekh 
- [ ] @kirolosessam

**Comment by Omarabdul3ziz** [comment]
https://github.com/Omarabdul3ziz/link_checker

**Comment by omarelsheekh** [comment]
https://github.com/omarelsheekh/codescalers2019linkcheck
