### ISSUE TITLE
ASCII Table generator

### ISSUE THREAD

**Issue by xmonader** [codescalersinternships/home#8]
To provide a decent way to render lists as a table in the commandline

- [ ] @OmarElawady 
- [ ] @Omarabdul3ziz 
- [ ] @omarelsheekh 
- [ ] @kirolosessam

**Comment by OmarElawady** [comment]
https://github.com/OmarElawady/ascii-table

**Comment by omarelsheekh** [comment]
https://github.com/omarelsheekh/codescalers2019AsciiTable
